authorName: Xiao HE
experimentName: tunning_model_1
trialConcurrency: 1
maxExecDuration: 4h
maxTrialNum: 30
trainingServicePlatform: local
# The path to Search Space
searchSpacePath: search_space.json
useAnnotation: false
advisor:
  builtinAdvisorName: BOHB
  classArgs:
    optimize_mode: maximize
    min_budget: 1
    max_budget: 27
    eta: 3
# The path and the running command of trial
trial:
  command: python main.py
  codeDir: .
  gpuNum: 1
localConfig:
  useActiveGpu: true
