authorName: Xiao HE
experimentName: tunning_model_1
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 30
trainingServicePlatform: local
# The path to Search Space
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: GPTuner
  classArgs:
    optimize_mode: maximize
    utility: 'ei'
    kappa: 5.0
    xi: 0.0
    nu: 2.5
    alpha: 1e-6
    cold_start_num: 10
    selection_num_warm_up: 100000
    selection_num_starting_points: 250
# The path and the running command of trial
trial:
  command: python main.py
  codeDir: .
  gpuNum: 1
localConfig:
  useActiveGpu: true
