authorName: Xiao HE
experimentName: tunning_model_2
trialConcurrency: 4
maxExecDuration: 40h
maxTrialNum: 30
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
trial:
  command: python main.py
  codeDir: .
  gpuNum: 1
localConfig:
  useActiveGpu: true
