authorName: Xiao HE
experimentName: tunning_model_2
trialConcurrency: 1
maxExecDuration: 40h
maxTrialNum: 30
trainingServicePlatform: local
# The path to Search Space
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: SMAC
# The path and the running command of trial
trial:
  command: python main.py
  codeDir: .
  gpuNum: 1
localConfig:
  useActiveGpu: true
